if(NOT DEFINED EMOJINEER)
  message(FATAL_ERROR "EMOJINEER executable path is required")
endif()
if(NOT DEFINED TEST_ROOT)
  message(FATAL_ERROR "TEST_ROOT is required")
endif()
file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}")
set(PURE "${TEST_ROOT}/pure.easm")
set(IMPORTING "${TEST_ROOT}/importing.easm")
file(WRITE "${PURE}" "EASM1\nbuffer scratch i64 4\nfunc main () -> i64 regs (i64,i64,i64)\n i64.const r0 0\n i64.const r1 21\n buffer.store.i64 scratch r0 r1\n buffer.load.i64 r2 scratch r0\n i64.add r2 r2 r1\n return r2\nend\nexport main main\n")
file(WRITE "${IMPORTING}" "EASM1\nimport net fixture.net network (i64) -> i64\nfunc main () -> i64 regs (i64,i64)\n i64.const r0 1\n call r1 net r0\n return r1\nend\nexport main main\n")
function(run_ok label)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "${label} failed (${result})\nstdout:\n${output}\nstderr:\n${error}")
  endif()
  set(LAST_OUTPUT "${output}" PARENT_SCOPE)
endfunction()
function(run_fail label needle)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(result EQUAL 0)
    message(FATAL_ERROR "${label} unexpectedly succeeded\n${output}")
  endif()
  string(FIND "${error}" "${needle}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "${label} did not report '${needle}'\nstdout:\n${output}\nstderr:\n${error}")
  endif()
endfunction()
run_ok("EASM check" "${EMOJINEER}" easm-check "${PURE}")
string(FIND "${LAST_OUTPUT}" "is valid EASM1" found_valid)
if(found_valid EQUAL -1)
  message(FATAL_ERROR "EASM check output missing validity receipt: ${LAST_OUTPUT}")
endif()
run_ok("EASM pure execution" "${EMOJINEER}" easm-run "${PURE}")
if(NOT LAST_OUTPUT STREQUAL "42\n")
  message(FATAL_ERROR "unexpected EASM execution output: ${LAST_OUTPUT}")
endif()
run_ok("EASM info" "${EMOJINEER}" easm-info "${PURE}")
foreach(needle "required capabilities: none" "buffers: 1" "exports: 1" "main <- main")
  string(FIND "${LAST_OUTPUT}" "${needle}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "EASM info missing '${needle}': ${LAST_OUTPUT}")
  endif()
endforeach()
run_ok("EASM canonical dump" "${EMOJINEER}" easm-dump "${IMPORTING}")
set(CANONICAL "${TEST_ROOT}/canonical.easm")
file(WRITE "${CANONICAL}" "${LAST_OUTPUT}")
run_ok("EASM canonical reparse" "${EMOJINEER}" easm-check "${CANONICAL}")
run_ok("EASM importing info" "${EMOJINEER}" easm-info "${IMPORTING}")
foreach(needle "required capabilities: network" "fixture.net" "capabilities=network")
  string(FIND "${LAST_OUTPUT}" "${needle}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "EASM importing report missing '${needle}': ${LAST_OUTPUT}")
  endif()
endforeach()
run_fail("EASM capability denial" "missing capability grant(s): network" "${EMOJINEER}" easm-run "${IMPORTING}")
run_fail("EASM missing adapter after grant" "EASM interop adapter registry is required" "${EMOJINEER}" easm-run "${IMPORTING}" --grant network)
run_fail("EASM inspection rejects runtime flags" "does not accept execution policy options" "${EMOJINEER}" easm-info "${PURE}" --grant network)
run_fail("EASM check rejects runtime flags" "does not accept execution policy options" "${EMOJINEER}" easm-check "${PURE}" --sandbox)
