if(NOT DEFINED EMOJINEER)
  message(FATAL_ERROR "EMOJINEER executable path is required")
endif()
if(NOT DEFINED TEST_ROOT)
  message(FATAL_ERROR "TEST_ROOT is required")
endif()
file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}")
set(SOURCE "${TEST_ROOT}/interop.emoji")
file(WRITE "${SOURCE}" "🔌 🧮 📜fixture.net📜 📜network📜 🔢 🫴 🔢 🤲\n📡 🚀 📜fixture.echo📜 🔢 🫴 🔢 🤲\n🛠️ 🚀 🫴 🍎 🤲\n📦 🍎\n🏁\n📝 🧮 🫴 1 🤲\n")
function(run_ok label)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "${label} failed (${result})\nstdout:\n${output}\nstderr:\n${error}")
  endif()
  set(LAST_OUTPUT "${output}" PARENT_SCOPE)
endfunction()
function(run_fail label needle)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(result EQUAL 0)
    message(FATAL_ERROR "${label} unexpectedly succeeded\n${output}")
  endif()
  string(FIND "${error}" "${needle}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "${label} did not report '${needle}'\nstdout:\n${output}\nstderr:\n${error}")
  endif()
endfunction()
run_ok("interop source" "${EMOJINEER}" interop "${SOURCE}")
foreach(needle "interop imports: 1" "fixture.net" "capabilities=network" "interop exports: 1" "fixture.echo")
  string(FIND "${LAST_OUTPUT}" "${needle}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "interop source report missing '${needle}':\n${LAST_OUTPUT}")
  endif()
endforeach()
run_ok("interop capabilities" "${EMOJINEER}" capabilities "${SOURCE}")
if(NOT LAST_OUTPUT STREQUAL "required capabilities: network\n")
  message(FATAL_ERROR "unexpected interop capability report: ${LAST_OUTPUT}")
endif()
set(BYTECODE "${TEST_ROOT}/interop.emjbc")
run_ok("compile v9 interop" "${EMOJINEER}" compile "${SOURCE}" -o "${BYTECODE}")
run_ok("interop bytecode" "${EMOJINEER}" interop "${BYTECODE}")
string(FIND "${LAST_OUTPUT}" "fixture.echo" found_export)
if(found_export EQUAL -1)
  message(FATAL_ERROR "serialized export missing from interop report: ${LAST_OUTPUT}")
endif()
run_ok("disasm v9 interop" "${EMOJINEER}" disasm "${BYTECODE}")
string(FIND "${LAST_OUTPUT}" "InteropCall" found_call)
if(found_call EQUAL -1)
  message(FATAL_ERROR "disassembly missing InteropCall: ${LAST_OUTPUT}")
endif()
run_fail("interop capability denial" "missing capability grant(s): network" "${EMOJINEER}" run "${SOURCE}")
run_fail("missing adapter after grant" "interop adapter registry is required" "${EMOJINEER}" run "${SOURCE}" --grant network)
run_fail("interop rejects runtime flags" "does not accept execution policy options" "${EMOJINEER}" interop "${SOURCE}" --grant network)
