if(NOT DEFINED EMOJINEER OR NOT DEFINED SOURCE_ROOT OR NOT DEFINED TEST_ROOT)
  message(FATAL_ERROR "EMOJINEER, SOURCE_ROOT, and TEST_ROOT are required")
endif()

file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}")
set(WEB "${SOURCE_ROOT}/examples/web_page.emjweb")
set(HTML "${TEST_ROOT}/page.html")

function(run_ok label)
  execute_process(COMMAND ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "${label} failed (${result})\nstdout:\n${output}\nstderr:\n${error}")
  endif()
  set(LAST_OUTPUT "${output}" PARENT_SCOPE)
endfunction()

run_ok("web-check" "${EMOJINEER}" web-check "${WEB}")
string(FIND "${LAST_OUTPUT}" "valid Emojineer web markup" valid_found)
if(valid_found EQUAL -1)
  message(FATAL_ERROR "web-check did not report validity")
endif()

run_ok("web-dump" "${EMOJINEER}" web-dump "${WEB}")
string(FIND "${LAST_OUTPUT}" "emojineer.web-ir.v1" schema_found)
if(schema_found EQUAL -1)
  message(FATAL_ERROR "web-dump missing typed IR schema")
endif()

run_ok("web-bindings" "${EMOJINEER}" web-bindings "${WEB}")
string(FIND "${LAST_OUTPUT}" "\"export\":\"web.greet\"" greet_binding)
string(FIND "${LAST_OUTPUT}" "\"event\":\"submit\"" submit_binding)
if(greet_binding EQUAL -1 OR submit_binding EQUAL -1)
  message(FATAL_ERROR "web-bindings missing explicit action contracts: ${LAST_OUTPUT}")
endif()

run_ok("web-build file" "${EMOJINEER}" web-build "${WEB}" -o "${HTML}")
if(NOT EXISTS "${HTML}")
  message(FATAL_ERROR "web-build did not create output file")
endif()
file(READ "${HTML}" BUILT_HTML)
string(FIND "${BUILT_HTML}" "<nav" nav_found)
string(FIND "${BUILT_HTML}" "<th scope=\"col\">" th_found)
string(FIND "${BUILT_HTML}" "<script" script_found)
string(FIND "${BUILT_HTML}" "javascript:" javascript_found)
if(nav_found EQUAL -1 OR th_found EQUAL -1)
  message(FATAL_ERROR "web-build output is missing semantic navigation/table markup")
endif()
if(NOT script_found EQUAL -1 OR NOT javascript_found EQUAL -1)
  message(FATAL_ERROR "web-build unexpectedly emitted executable script surface")
endif()

execute_process(
  COMMAND "${EMOJINEER}" web-check "${WEB}" --grant network
  RESULT_VARIABLE grant_result OUTPUT_VARIABLE grant_output ERROR_VARIABLE grant_error)
if(grant_result EQUAL 0)
  message(FATAL_ERROR "web-check unexpectedly accepted execution-policy grants")
endif()
string(FIND "${grant_error}" "does not accept execution policy options" grant_denied)
if(grant_denied EQUAL -1)
  message(FATAL_ERROR "web-check grant rejection changed: ${grant_error}")
endif()
