#include "emojineer/parser.hpp"
#include <sstream>
#include <stdexcept>
#include <utility>
namespace emojineer {
Parser::Parser(std::vector<Token> tokens):tokens_(std::move(tokens)){}
ast::Program Parser::parse(){ast::Program program;skip_newlines();while(!check(TokenKind::Eof)){if(check(TokenKind::Else)||check(TokenKind::End))error(peek(),"unexpected block marker");program.statements.push_back(statement());skip_newlines();}return program;}
ast::StmtPtr Parser::statement(){if(check(TokenKind::Var))return var_declaration();if(check(TokenKind::Assign))return assignment();if(check(TokenKind::Print))return print_statement();if(check(TokenKind::Return))return return_statement();if(check(TokenKind::Function))return function_declaration();if(check(TokenKind::If))return if_statement();if(check(TokenKind::While))return while_statement();error(peek(),"expected a statement (🐍, ✏️, 📝, 📦, 🛠️, 🤔, or 🔁)");}
ast::StmtPtr Parser::var_declaration(){const Token start=advance();const Token name=consume(TokenKind::Identifier,"expected an emoji identifier after 🐍");std::optional<ast::DeclaredType> type;if(match(TokenKind::TypeNumber))type=ast::DeclaredType::Number;else if(match(TokenKind::TypeString))type=ast::DeclaredType::String;else if(match(TokenKind::TypeBool))type=ast::DeclaredType::Bool;consume(TokenKind::Equal,"expected 🟰 in variable declaration");auto init=expression();consume_line_end();auto s=std::make_unique<ast::VarDecl>();s->line=start.line;s->name=name.canonical;s->declared_type=type;s->initializer=std::move(init);return s;}
ast::StmtPtr Parser::assignment(){const Token start=advance();const Token name=consume(TokenKind::Identifier,"expected an emoji identifier after ✏️");consume(TokenKind::Equal,"expected 🟰 in assignment");auto value=expression();consume_line_end();auto s=std::make_unique<ast::Assignment>();s->line=start.line;s->name=name.canonical;s->value=std::move(value);return s;}
ast::StmtPtr Parser::print_statement(){const Token start=advance();auto expr=expression();consume_line_end();auto s=std::make_unique<ast::PrintStmt>();s->line=start.line;s->expression=std::move(expr);return s;}
ast::StmtPtr Parser::return_statement(){const Token start=advance();auto expr=expression();consume_line_end();auto s=std::make_unique<ast::ReturnStmt>();s->line=start.line;s->expression=std::move(expr);return s;}
ast::StmtPtr Parser::function_declaration(){const Token start=advance();const Token name=consume(TokenKind::Identifier,"expected function emoji after 🛠️");consume(TokenKind::GroupStart,"expected 🫴 before function parameters");std::vector<std::string> params;while(!check(TokenKind::GroupEnd)){if(check(TokenKind::Eof)||check(TokenKind::Newline))error(peek(),"expected 🤲 after function parameters");const Token p=consume(TokenKind::Identifier,"function parameters must be emoji identifiers");params.push_back(p.canonical);}consume(TokenKind::GroupEnd,"expected 🤲 after function parameters");consume_line_end();skip_newlines();auto body=block_until(TokenKind::End);consume(TokenKind::End,"expected 🏁 to close 🛠️ function");consume_line_end();auto s=std::make_unique<ast::FunctionDecl>();s->line=start.line;s->name=name.canonical;s->parameters=std::move(params);s->body=std::move(body);return s;}
ast::StmtPtr Parser::if_statement(){const Token start=advance();auto condition=expression();consume_line_end();skip_newlines();auto then_branch=block_until(TokenKind::Else,TokenKind::End);std::vector<ast::StmtPtr> else_branch;if(match(TokenKind::Else)){consume_line_end();skip_newlines();else_branch=block_until(TokenKind::End);}consume(TokenKind::End,"expected 🏁 to close 🤔 block");consume_line_end();auto s=std::make_unique<ast::IfStmt>();s->line=start.line;s->condition=std::move(condition);s->then_branch=std::move(then_branch);s->else_branch=std::move(else_branch);return s;}
ast::StmtPtr Parser::while_statement(){const Token start=advance();auto condition=expression();consume_line_end();skip_newlines();auto body=block_until(TokenKind::End);consume(TokenKind::End,"expected 🏁 to close 🔁 block");consume_line_end();auto s=std::make_unique<ast::WhileStmt>();s->line=start.line;s->condition=std::move(condition);s->body=std::move(body);return s;}
std::vector<ast::StmtPtr> Parser::block_until(TokenKind first,TokenKind second){std::vector<ast::StmtPtr> block;skip_newlines();while(!check(TokenKind::Eof)&&!check(first)&&!check(second)){block.push_back(statement());skip_newlines();}if(check(TokenKind::Eof))error(peek(),"unterminated block; expected 🏁");return block;}
ast::ExprPtr Parser::expression(){return equality();}
ast::ExprPtr Parser::equality(){auto expr=comparison();while(match(TokenKind::Equal)){const Token op=previous();auto r=comparison();auto b=std::make_unique<ast::BinaryExpr>();b->line=op.line;b->left=std::move(expr);b->op=op.kind;b->right=std::move(r);expr=std::move(b);}return expr;}
ast::ExprPtr Parser::comparison(){auto expr=term();while(check(TokenKind::Less)||check(TokenKind::Greater)){const Token op=advance();auto r=term();auto b=std::make_unique<ast::BinaryExpr>();b->line=op.line;b->left=std::move(expr);b->op=op.kind;b->right=std::move(r);expr=std::move(b);}return expr;}
ast::ExprPtr Parser::term(){auto expr=factor();while(check(TokenKind::Add)||check(TokenKind::Subtract)){const Token op=advance();auto r=factor();auto b=std::make_unique<ast::BinaryExpr>();b->line=op.line;b->left=std::move(expr);b->op=op.kind;b->right=std::move(r);expr=std::move(b);}return expr;}
ast::ExprPtr Parser::factor(){auto expr=unary();while(check(TokenKind::Multiply)||check(TokenKind::Divide)||check(TokenKind::Modulo)){const Token op=advance();auto r=unary();auto b=std::make_unique<ast::BinaryExpr>();b->line=op.line;b->left=std::move(expr);b->op=op.kind;b->right=std::move(r);expr=std::move(b);}return expr;}
ast::ExprPtr Parser::unary(){if(match(TokenKind::Subtract)||match(TokenKind::Not)){const Token op=previous();auto e=std::make_unique<ast::UnaryExpr>();e->line=op.line;e->op=op.kind;e->right=unary();return e;}return primary();}
ast::ExprPtr Parser::primary(){if(match(TokenKind::Number)){auto e=std::make_unique<ast::LiteralExpr>();e->line=previous().line;e->value=std::stod(previous().literal);return e;}if(match(TokenKind::String)){auto e=std::make_unique<ast::LiteralExpr>();e->line=previous().line;e->value=previous().literal;return e;}if(match(TokenKind::True)||match(TokenKind::False)){auto e=std::make_unique<ast::LiteralExpr>();e->line=previous().line;e->value=previous().kind==TokenKind::True;return e;}if(match(TokenKind::Identifier)){const Token name=previous();if(match(TokenKind::GroupStart)){auto call=std::make_unique<ast::CallExpr>();call->line=name.line;call->callee=name.canonical;while(!check(TokenKind::GroupEnd)){if(check(TokenKind::Eof)||check(TokenKind::Newline))error(peek(),"expected 🤲 after function arguments");call->arguments.push_back(expression());}consume(TokenKind::GroupEnd,"expected 🤲 after function arguments");return call;}auto e=std::make_unique<ast::VariableExpr>();e->line=name.line;e->name=name.canonical;return e;}if(match(TokenKind::Input)){auto e=std::make_unique<ast::InputExpr>();e->line=previous().line;return e;}if(match(TokenKind::GroupStart)){auto e=expression();consume(TokenKind::GroupEnd,"expected 🤲 after grouped expression");return e;}error(peek(),"expected an expression");}
static const Token& eof_token(){static Token eof{TokenKind::Eof,"","","",0,0};return eof;}
bool Parser::match(TokenKind kind){if(!check(kind))return false;advance();return true;}bool Parser::check(TokenKind kind)const{return peek().kind==kind;}const Token& Parser::advance(){if(!check(TokenKind::Eof)&&current_<tokens_.size())++current_;return previous();}const Token& Parser::previous()const{if(current_==0||current_>tokens_.size())return eof_token();return tokens_[current_-1];}const Token& Parser::peek()const{if(current_>=tokens_.size())return eof_token();return tokens_[current_];}const Token& Parser::consume(TokenKind kind,const std::string& message){if(check(kind))return advance();error(peek(),message);}void Parser::consume_line_end(){if(match(TokenKind::Newline)||check(TokenKind::Eof))return;error(peek(),"expected end of line");}void Parser::skip_newlines(){while(match(TokenKind::Newline)){} }[[noreturn]]void Parser::error(const Token& token,const std::string& message)const{std::ostringstream out;out<<"line "<<token.line<<", column "<<token.column<<": "<<message;if(!token.lexeme.empty())out<<" near '"<<token.lexeme<<"'";throw std::runtime_error(out.str());}
}
