include(GNUInstallDirs)

install(TARGETS emojineer emji emojineer-lsp
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})

install(DIRECTORY "${CMAKE_SOURCE_DIR}/docs/"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/emojineer/docs")
install(DIRECTORY "${CMAKE_SOURCE_DIR}/examples/"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/emojineer/examples")
install(FILES "${CMAKE_SOURCE_DIR}/README.md"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/emojineer")

set(CPACK_PACKAGE_NAME "Emojineer")
set(CPACK_PACKAGE_VENDOR "Emojineer")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY
    "Sovereign emoji-native programming language and toolchain")
string(TOLOWER "${CMAKE_SYSTEM_NAME}" EMOJINEER_PACKAGE_OS)
if(CMAKE_SYSTEM_PROCESSOR)
    set(EMOJINEER_PACKAGE_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
else()
    set(EMOJINEER_PACKAGE_ARCH "unknown")
endif()

set(CPACK_PACKAGE_FILE_NAME
    "emojineer-${PROJECT_VERSION}-${EMOJINEER_PACKAGE_OS}-${EMOJINEER_PACKAGE_ARCH}")
set(CPACK_PACKAGE_CHECKSUM "SHA256")
set(CPACK_MONOLITHIC_INSTALL ON)
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY OFF)

if(WIN32)
    set(CPACK_GENERATOR "ZIP")
else()
    set(CPACK_GENERATOR "TGZ")
endif()

include(CPack)
